### PR TITLE
Fix issue with completion of animation group on iOS 10

### PR DESCRIPTION
**Pull request by mikeger**
Our crash analytics showed that on iOS 10 our app is crashing because the completion method of `UIView+MTAnimation` `animationDidStart:` is called with argument of type `CAAnimationGroup` which does not seem to have the `keyPath` property, which seems logical. 

Solution is to guard the actions that require `keyPath` to animations that support it.

### CODE REVIEW

**Comment by atomkirk** [comment]
It's been a long time since I've used CAAnimationGroup. Would it be logical to loop through the items in the group and use the keypath on each one?

**Comment by mikeger** [comment]
@atomkirk on the first look yes, but looking on the implementation:
the `animationCompletions` is populated by `MTAnimation`'s own code only in `addAnimation:delay:forKey:range:options:perspective:` method, which is called only for `CAKeyframeAnimation` instances. This means we need to care only about our own animation completions, and `CAAnimationGroup` cannot be the one that we created.

**Comment by atomkirk** [comment]
Awesome. Can you add a code comment right above your addition explaining this and I'll merge this right in? (I just know a year from now I'm going to be so confused why that code is there)

**Comment by mikeger** [comment]
@atomkirk done!

**Pull request merged**
